---
- name: Check dependencies
  become: true
  ansible.builtin.package:
    name:
      - base-devel
      - git
    state: present

- name: Clone Yay repository
  ansible.builtin.git:
    repo: "{{ yay_repo }}"
    dest: "{{ yay_dir }}"

- name: Build and install Yay
  ansible.builtin.command:
    argv: 
      - makepkg 
      - -si 
      - --noconfirm
    chdir: "{{ yay_dir }}"

