---
- name: Check dependencies
  become: true
  ansible.builtin.package:
    name:
      - base-devel
      - git
    state: present

- name: Clone Yay repository
  ansible.builtin.git:
    repo: "{{ yay_repo }}"
    dest: "{{ yay_dir }}"

- name: Build Yay package
  ansible.builtin.command:
    cmd: makepkg -f --noconfirm
    chdir: "{{ yay_dir }}"

- name: Install built Yay package
  ansible.builtin.shell:
    cmd: pacman -U --noconfirm *.pkg.tar.zst
    chdir: "{{ yay_dir }}"
  become: true
