---
- name: Init collections
  hosts: localhost
  tasks:
    
    - name: Run install command
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - collection
          - install
          - -r
          - requirements.yaml

    - name: Install ansible-lint
      become: true
      ansible.builtin.package:
        name: ansible-lint
