---
- name: Add g14 repo into pacman's database
  become: true
  block:
    - name: Add repo sign key to pacman-key
      ansible.builtin.command: "{{ add_repo_script }}"

    - name: Update the system
      ansible.builtin.command: pacman -Syu --noconfirm

- name: Install asusctl
  become: true
  block:
    - name: Install packages
      ansible.builtin.package:
        name:
          - asusctl
          - power-profiles-daemon
        state: present

    - name: Enable power-profiles-daemon service
      ansible.builtin.service:
        name: power-profiles-daemon
        state: started
        enabled: true

- name: Install rog-control-center
  become: true
  ansible.builtin.package:
    name: rog-control-center
    state: present
