---
- name: Ensure dependencies
  ansible.builtin.package:
    name:
      - iwd
    state: present

- name: Enable iwd.service
  ansible.builtin.systemd_service:
    name: iwd
    enabled: true
    state: started

- name: Enable DNS resolver (systemd-resolved)
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started
  
- name: Set Google DNS in resolver's config file
  ansible.builtin.blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    backup: yes

- name: Enable Network Service
  ansible.builtin.systemd_service:
    name: systemd-networkd
    enabled: true
    state: started

- name: Restart DNS resolver to load the configuration
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Set up routing table
  ansible.builtin.command:
    argv:
      - ip
      - route
      - add
      - "default via 192.168.1.1 dev wlan0"

- name: Restart Network Service 
  ansible.builtin.systemd_service:
    name: systemd-networkd
    state: restarted
