---
- name: Install package
  become: true
  ansible.builtin.package:
    name:
      - kitty
    state: present

- name: Install essential stuff
  include_tasks: ./essential.yaml

- name: Add config file
  include_tasks: ./config.yaml
