---
- name: Ensure that git exists
  become: true
  ansible.builtin.package:
    name:
      - git
      - less
    state: present

- name: Set global user's name
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.name
      - "{{ user_name }}"


- name: Set global user's email
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.email
      - "{{ user_email }}"
