---
- name: Ensure dependencies
  ansible.builtin.package:
    name:
      - iwd
    state: present

- name: Set the hostname
  ansible.builtin.command:
    argv:
      - hostnamectl
      - hostname
      - phenchua-laptop

- name: Enable iwd's service
  ansible.builtin.systemd_service:
    name: iwd
    enabled: true
    state: started

- name: Ensure that iwd's configuration directory exists
  ansible.builtin.file:
    path: /etc/iwd
    state: directory

- name: Ensure that iwd's configuration file exists
  ansible.builtin.file:
    path: /etc/iwd/main.conf
    state: touch

- name: Turn on iwd's internal DHCP client
  ansible.builtin.blockinfile:
    path: /etc/iwd/main.conf
    block: |
      [General]
      EnableNetworkConfiguration=true
    backup: true

- name: Enable DNS resolver (systemd-resolved)
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true
    state: started

- name: Add symbolic link so that DNS is working correctly for softwares that read /etc/resolv.conf directly
  ansible.builtin.command:
    argv:
      - ln
      - -sf
      - ../run/systemd/resolve/stub-resolv.conf
      - /etc/resolv.conf

- name: Configure hosts
  block:

    - name: Add ipv4 localhost
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 localhost"

    - name: Add ipv6 localhost
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "::1 localhost"
