---
- name: Install packages
  ansible.builtin.package:
    name:
      - grub
      - efibootmgr
      - os-prober
      - linux # incase vmlinuz-linux is not found
    state: present

- name: Run grub-install
  become: true
  ansible.builtin.command:
    argv:
      - grub-install
      - --efi-directory={{ efi_dir }}
      - --bootloader-id=GRUB
      - --modules=tpm
      - --disable-shim-lock
  register: result
  changed_when: result.rc == 0

- name: Enable os-prober for grub to detect other systems
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^#GRUB_DISABLE_OS_PROBER=false$"
    line: "GRUB_DISABLE_OS_PROBER=false"

- name: Set grub menu's timeout to 10000 seconds
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT=10000"

- name: Generate Grub's configuration
  ansible.builtin.command:
    argv:
      - grub-mkconfig
      - --output=/boot/grub/grub.cfg
  register: result
  changed_when: result.rc == 0

- name: Get config file's status
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: conf_file_status

- name: Print config file's state
  ansible.builtin.debug:
    msg: "Config file exist: {{ conf_file_status.stat.exists }}"

- name: Print successful message
  ansible.builtin.debug:
    msg: "Generate grub's config file successfully."
  when: conf_file_status.stat.exists

- name: Setup secure boot support
  include_tasks: ./secure-boot.yml
