---
- name: Install packages for archlinux
  become: true
  community.general.pacman:
    name:
      - neovim
      - gcc
      - pnpm # tree-sitter-cli
      - wl-clipboard
      - fd # Search
      - ripgrep # Search
      - fzf # Search
      - ttf-hack-nerd
      - unzip # Mason
      - npm # Mason
      - rust # Mason
      - go # Mason / LSP
      - lazygit
      - bat # For fzf-lua
      - maven # For java-language-server
      - imagemagick # image.nvim
      - d2

- name: Apply chezmoi nvim dotfiles
  ansible.builtin.command: chezmoi apply ~/.config/nvim
  changed_when: false
