---
- name: Install packages for archlinux
  become: true
  community.general.pacman:
    name:
      - neovim
      - gcc
      - wl-clipboard
      - fd # Search
      - ripgrep # Search
      - fzf # Search
      - ttf-hack-nerd
      - unzip # Mason
      - npm # Mason
      - rust # Mason
      - go # Mason / LSP
      - lazygit
      - bat # For fzf-lua
      - maven # For java-language-server
      - imagemagick # image.nvim
      - d2
      - base-devel # Compile C codes
      - tree-sitter-cli
      - jdk21-openjdk

- name: Apply chezmoi nvim dotfiles
  ansible.builtin.command:
    cmd: chezmoi apply ~/.config/nvim
    creates: ~/.config/nvim
