---
- name: Install packages
  ansible.builtin.include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: Install tree-sitter-cli via pnpm
  community.general.pnpm:
    name: tree-sitter-cli
    global: true
