---
- name: Install packages
  become: true
  ansible.builtin.package:
    name: 
      - neovim
      - wl-clipboard
      - fd
      - ripgrep
      - ttf-hack-nerd 
    state: present

- name: Make install dependencies script runnable
  ansible.builtin.file:
    path: "~/.config/nvim/install-dependency.sh"
    mode: u=rwx

- name: Install all nvim dependencies
  ansible.builtin.command: ~/.config/nvim/install-dependency.sh
